version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:3000
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
    environment:
      - GO_ENV=development