# docker-compose -f docker-compose.dev.yml up --build

FROM golang:1.22.5-alpine

WORKDIR /app

# INSTALL GIT TO SYNC TO REMOTE REPO INSIDE CONTAINER
RUN apk add --no-cache git

# INSTALL AIR FOR AUTO RELOAD | DO air init TO CONFIGURE
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
